version: "3.7"

services:
  web:
    build: .
    image: web
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./app/:/usr/src/app/app/
      - ./tests/:/usr/src/app/tests/
    ports:
      - 8000:8000
    environment:
      - CELERY_BACKEND=redis://redis:6379
      - CELERY_BROKER=redis://redis:6379
      - DATABASE_URL=postgresql://hello_fastapi:hello_fastapi@db/hello_fastapi_dev
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  db:
    image: postgres:12.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_fastapi
      - POSTGRES_PASSWORD=hello_fastapi
      - POSTGRES_DB=hello_fastapi_dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]

  celery:
    image: web
    volumes:
      - ./app/:/usr/src/app/app/
    command: celery -A app.tasks worker --loglevel=info
    environment:
      - CELERY_BACKEND=redis://redis:6379
      - CELERY_BROKER=redis://redis:6379
    depends_on:
      - redis
      - web

  monitor:
    image: web
    ports:
      - 5555:5555
    command: celery flower -A app.tasks --port=5555 --broker=redis://redis:6379
    depends_on:
      - redis
      - web

  redis:
    image: redis:5.0.8-alpine

volumes:
  postgres_data:
