version: '3.7'

services:
  web:
    build: .
    image: web
    command: gunicorn app.main:app --reload --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    environment:
      - CELERY_BACKEND=redis://redis:6379
      - CELERY_BROKER=redis://redis:6379
      - DATABASE_URL=postgresql://hello_fastapi:hello_fastapi@db/hello_fastapi_dev
    depends_on:
      - db
      - redis

  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_fastapi
      - POSTGRES_PASSWORD=hello_fastapi
      - POSTGRES_DB=hello_fastapi_dev

  celery:
    image: web
    volumes:
      - ./:/usr/src/app
    command: celery -A app.tasks worker --loglevel=info
    environment:
      - CELERY_BACKEND=redis://redis:6379
      - CELERY_BROKER=redis://redis:6379
    depends_on:
      - redis
      - web

  monitor:
    image: web
    ports:
      - 5555:5555
    command:  flower -A app.tasks --port=5555 --broker=redis://redis:6379
    depends_on:
      - redis
      - web

  redis:
    image: redis:5.0.3-alpine

volumes:
  postgres_data:
